apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: database-group
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pass123
        ports:
        - containerPort: 3306
