apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: mypvcnginx
        persistentVolumeClaim:
          claimName: nginx-pvc
      initContainers:
      - name: init-nginx
        image: busybox
        volumeMounts:
        - name: mypvcnginx
          mountPath: "/usr/share/nginx/html"
        command: ['sh', '-c', 'echo "<h1>Hello from Kubernetes</h1>" > /usr/share/nginx/html/index.html']
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: mypvcnginx
          mountPath: "/usr/share/nginx/html"
