apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hallo-namespace
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: LoadBalancer
