apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: ExternalName
  externalName: cat-fact.herokuapp.com
  sessionAffinity: None
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443