kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgadmin-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/pgadmin"