apiVersion: v1
kind: Service
metadata:
  name: pgadmin # Sets service name
  labels:
    app: pgadmin # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  selector:
    app: pgadmin    
  ports:
    - port: 8080
      targetPort: 80


