kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pv-claim  # Sets name of PVC
  labels:
    app: pgadmin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 1Gi  # Sets volume size