apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: MY_CONFIG
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: key1