apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-demo101
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mystorageclass-demo